<%@ page language="java" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      .name {font-style: italic;font-family:"Times New Roman"}
      span {font-size:large;font-family: "Times New Roman";}
      img {
        width: 600px;
        height: 250px;
        top:50%;
        left:50%;
        margin-top: 0px; 
        margin-left: 0px; 
      }
      .img1{
        display: table-cell;
            width: 650px;
            height: 300px;
            vertical-align: middle;
            text-align: center;
            margin: auto;
            margin-left: 150px;
            top:50%;
            left:50%;
      }
      p {
        font-family: "Times New Roman";
      }
    </style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Causal Learner </title>
  </head>
  <body>
    <div>
      <h1>Causal Learner: A Toolbox for Causal Structure and Markov Blanket Learning</h1>
    </div>
    <div class="name">
      <p>Zhaolong Ling, Anhui University</p>
      <p>Kui Yu, Hefei University of Technology</p>
      <p>Hao Wang, Hefei University of Technology</p>
      <p>Yiwen Zhang, Anhui University</p>
      <p>Lin Liu, University of South Australia</p>
      <p>Jiuyong Li, University of South Australia</p> 
    </div>
    <span>Causal Learner is an easy-to-use open source toolbox for causal structure and Markov blanket (MB) learning. The relationship between global causal structure, 
        local causal structure, and MB is shown in Figure 1 (T is a target node in black).<br/><br/>
        Causal Learner provides discrete data and continuous data generating functions, causal structure learning and MB learning algorithms, and algorithm evaluation functions.
        The data generation part of Causal Learner is written in R language, and the rest of Causal Learner is written in MATLAB. Causal Learner is is an open-source version of the will-known causality learning toolbox Causal Explorer, which makes research efforts on causal structure learning and MB learning much easier.<br/>
    </span>
      
    <div class="img1">
      <img src="/img/relationships.jpg" alt="">
      <br>
      <p>Figure 1: Relationships</p>
    </div>
      
    <div>
      <h1>Architecture of Causal Learner</h1>
      <span>
        Figure 2 illustrates the hierarchical architecture of Causal Learner, in which we also compare it with another toolbox for learning causal structure and MB, Causal Explorer. Generally, Causal Explorer only provides some algorithms, and it was developed 10 years ago, many new algorithms on learning causal structure and MB have been proposed. By contrast, Causal Learner conceives a more ambitious blueprint. It attempts to support the entire causal structure and MB learning procedure including data generation, state-of-the-art algorithms, and algorithm evaluations.
      </span>
      <br>
      <div class="img1">
        <img src="/img/Architecture.jpg">
        <br>
        <p>Figure 2: Architecture</p>
      </div>
      
    </div>
    <div>
      <h1>Data</h1>
      <span>
        In data layer, Causal Learner generates two types of data: discrete data and continuous 
        data. The data are simulated from various benchmark BNs (written in R language), and the details of each BN are shown in Table 1. The data can already be generated by the bnlearn toolbox, but the generated data is encapsulated in R language classes and cannot be easily used by researchers. The work that we have done is to output the generated data into text for easy use.
        <br>  
      </span>
      <br>
      <div class="img1">
        <img src="/img/Benchmark Bayesian networks.png">
      <br>
      <p>Table 1: Benchmark Bayesian networks</p>  
      </div>     
    </div>
    <div>
      <h1>Algorithm</h1>
      <span>
        In algorithm layer, Causal Learner implements 7 global causal structure learning algorithms, 4 local causal structure learning algorithms, and 15 MB learning algorithms (written in Matlab). Table 2 gives a list of all algorithms. To ensure the correctness of the algorithms we implement, 1) Unless the original implementations of algorithms are not released, we always try to integrate the original versions rather than re-implementing them. 2) Using the same data and evaluation functions, the algorithms in Causal Learner are comparable with that of Causal Explorer in accuracy, and achieve far better efficiency. 
      </span>
      <div class="img1">
        <img src="/img/Algorithms.png">
        <br>
        <p>Table 2: Algorithms (Learner represents Causal Learner and Explorer denotes Causal Explorer, • indicates that there is an algorithm in the corresponding toolbox, while ◦ indicates that the algorithm is not in the toolbox.)</p>
      </div>
    </div>
      <h1>Evaluation</h1>
      <span>
        In evaluation layer, Causal Learner provides abundant evaluation metrics for evaluating causal structure and MB learning algorithms (written in Matlab). In terms of accuracy, global and local causal structure learning algorithms use the same 7 metrics: Ar_F1, Ar_precision, Ar_recall, SHD, Miss, Extra, and Reverse, MB learning algorithms use 3 metrics: Adj_F1, Adj_precision, and Adj_recall. In terms of effiffifficiency, global causal structure learning algorithms use running time, while local causal structure and MB learning algorithms use the number of conditional independence tests and running time.
      </span>
      <br>
    <div>
    <div>
      <h1>Usage Example</h1>
      <span>
        Causal Learner comes with a manual that details algorithms, evaluation metrics, and how each function is used. Causal Learner uses a cleaner input format than Causal Explorer, and Figures 3-5 show the examples of global causal structure learning, local causal structure learning, and Markov blanket learning, respectively
      </span>
      <br>
      
    <div class="img1">
      <img src="/img/An example of global causal structure learning.jpg">
      <br>
      <p>Figure 3: An example of global causal structure learning</p>
    </div>
    <br>   
      <div class="img1">
        <img src="/img/An example of local causal structure learning.jpg">
        <br>
        <p>Figure 4: An example of local causal structure learning</p>
      </div>
      <br>
      <div class="img1">
        <img src="/img/An example of Markov blanket learning.jpg">
        <br>
        <p>Figure 5: An example of Markov blanket learning</p>
      
      
    </div>
    <h1>Click here to download the latest stable release of Causal Learner.</h1>
    <br>
    </div>  
  </div>
  </body>
  </html>